### ISSUE TITLE
Problems using the package builder

### ISSUE THREAD

**Issue by raducoravu** [oxygenxml/Translation-Package-Builder#15]
The ZIP file was not generated because of two xrefs that were reported as modified files in the xhtml report:

    topics/status_information_on_bed_view_2.dita#status_information_on_bed_view_2/table_ufb_hg2_cy
    topics/status_information_on_bed_view_2.dita#status_information_on_bed_view_2/table_rvn_c4k_by

When I manually removed the xref in the source topic, the ZIP file was generated immediately. Note that there was no error message when the ZIP file was not generated.

Another improvement could be to generate the ZIP file even if some files are missing and report them. I tested the add-on on a sample project (exported from a real ditamap) where some topics were missing because they were only called through xref references and not in the ditamap (I'm not saying that's a good writing practice...). I had an error message that the files were missing. IMHO, it could be interesting to generate the ZIP file anyway and report the missing topics.

**Comment by AdrianSorop** [comment]
Even if a file is not referred directly in the ditamap it's added to the translation ZIP (if xref references are used).
Should this happen for conrefs?

**Comment by raducoravu** [comment]
Yes, all directly and indirected resources should be exported to the ZIP file.

**Comment by SanFanDocu** [comment]
Have the same issue (no zip file generated, no error message) with Oxygen 20.1. Any idea how to narrow down the cause?

**Comment by raducoravu** [comment]
@SanFanDocu Maybe you could uninstall the add-on and re-install it again just to be sure. If problem persists we would somehow need to know how your project is structured. Are you using a DITA DTD specialization? Are you referring to the topics using topicref or are you using keydef (and have a special DITA Map with key definitions) and then use topicref with keyref in the main DITA Map?
