### ISSUE TITLE
Prerequisites for applying package?

### ISSUE THREAD

**Issue by miriam-orion** [oxygenxml/Translation-Package-Builder#32]
I translated a package using Madcap Lingo, exported the translated DITA files, created a ZIP of it and stored the ZIP in the DITA project folder.
When applying the ZIP on the .ditamap I get the following error messages: 

1st error: Failed to apply package because:invalid CEN header (bad entry name)
2nd error: Failed to apply package because:Cannot invoke "java.util.List.Iterator()" because "filePaths" is null.

So something about the ZIP or the files exported from Lingo do not meet the add-on's expectations.  What should the ZIP contents look like or rather what are the prerequisites for applying the package?

**Comment by raducoravu** [comment]
An error like this "invalid CEN header (bad entry name)" seems to indicate the ZIP is somehow corrupt.
How did you create the ZIP file? We are using internally quite a lot a free application named 7-Zip, maybe you could give it a try.

Other than that,let's recap the workflow:
1) You exported a zip from Oxygen containing only the files which have changed
2) You unzipped that and translated it using Madcap lingo
3) You took the result files given by Madcap and preserving the file structure of the exported zip you zipped them again and applied them using the Oxygen plugin.

Is that more or less what you did?

**Comment by miriam-orion** [comment]
Thank you for the quick answer. I used 7-Zip, too.
But I think I found the cause now. The project folder is stored in the C-drive (so that I do not run into the Windows problem with the file path length restriction anytime soon). It seems like admin privileges are required to read/write. 
When I move everything to the Windows standard Documents folder, for example, everything runs smoothly.

**Comment by raducoravu** [comment]
Thanks for digging into this, it is correct that Oxygen just like any other Windows application if started from the user account cannot modify/write content on the C:\ drive. We cannot control this, but it is indeed advisable to have content in a place with full read/write access to all applications that you are using to change it.
